### PR TITLE
Responsive version for the website

### PR DESCRIPTION
**Pull request by soul-wish**
Enable responsive version for the website (add ability to check conf website on mobile devices and tablets). @artyomtrityak check it please locally, before merging (in case you are going to :) ).

### CODE REVIEW

**Comment by ghaiklor** [comment]
@soul-wish Only speakers has responsive design. All other blocks is not responsive.

**Comment by soul-wish** [comment]
Hm.. Strange. I checked few times before submitting this PR. All blocks are responsive (as they should be).
screen-iphone
screen-ipad
Can you check it one more time? Or just provide me with more details regarding the issue on your side?

**Comment by ghaiklor** [comment]
Here I've opened your branch in Safari on MBP.

**Comment by ghaiklor** [comment]
@soul-wish and here another responsive website opened in the same way.

**Comment by soul-wish** [comment]
Oh.. Thanks for the screenshots, @ghaiklor. It was  my fault with incorrect min-width css property (and it was just OK for Chrome and Firefox). Anyway, it was fixed. Can you recheck it?

**Comment by ghaiklor** [comment]
@artyomtrityak @soul-wish yeah, seems that now is ok. I'm merging it.
Anyway it don't break existing site :smiley:

**Comment by ghaiklor** [comment]
Forgot to merge, sorry :beers:

**Pull request merged**
